[package]
name = "rusclog"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Mannsverk Eliassen"]

[dependencies]
glam = "0.30.5"
sokol = { version="*", git="https://github.com/floooh/sokol-rust.git" }
