[package]
name = "ecosys"
version = "0.1.0"
edition = "2021"

[dependencies]
rusclog = { path = "../../" }
glam = "0.30.5"
rand = "0.9.2"
sokol = { version="*", git="https://github.com/floooh/sokol-rust.git" }

[[bin]]
name = "ecosys"
path = "src/main.rs"
